apiVersion: v1
kind: Service
metadata:
  name: facade-api-service
  labels:
    app: facade-api
spec:
  selector:
    app: facade-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3004
  type: NodePort
