apiVersion: v1
kind: Service
metadata:
  name: image-to-text-service
  labels:
    app: image-to-text
spec:
  selector:
    app: image-to-text
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3001
  type: NodePort
