apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-frontend-deployment
  labels:
    app: simple-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-frontend
  template:
    metadata:
      labels:
        app: simple-frontend
    spec:
      containers:
      - name: simple-frontend
        image: simple-frontend:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
