apiVersion: v1
kind: Service
metadata:
  name: simple-frontend-service
  labels:
    app: simple-frontend
spec:
  selector:
    app: simple-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort
