apiVersion: v1
kind: Service
metadata:
  name: translate-api-service
  labels:
    app: translate-api
spec:
  selector:
    app: translate-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3002
  type: NodePort
